wds/core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, Trade, reqcreate,received_request,sent_request,accept_request,decline_request,cancel_request,report,history
from core import views
app_name="core"

urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('userlogin/',views.user_login,name='userlogin'),
    path('stocks/',views.stock_display,name='stocks'),
    path('userlogout/',views.userlogout,name='userlogout'),
    path('news/',views.news,name='news'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('news/',views.news,name='news'),
    path('report/',report,name='report'),
    path('buy-sell-form/',Trade.as_view(),name='buy-sell-form'),
    path('reqcreate/',reqcreate,name='createrequest'),
    path('receivedreq/',received_request,name='receivedreq'),
    path('sentreq/',sent_request,name='sentreq'),
    path('report/',report,name='report'),
    path('transaction-history/',history,name='transaction-history'),
    path('accept_request/<friend_request_id>',accept_request,name='accept-request'),
    path('decline_request/<friend_request_id>',decline_request,name='decline-request'),
    path('cancel_request/<friend_request_id>',cancel_request,name='cancel-request'),
    path('',home,name="home"),
    
]

wds/wds/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('register/', core_views.register, name='register'),
    path('',include('core.urls',namespace='core')),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

wds/templates/buy-sell-form.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <h1>Fill the form to buy/sell stocks!</h1>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>
</div>



{% endblock %}

wds/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- <link href="{% static '/css/css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/dashboard.css' %}"> -->

    
    <style>
      *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}



body {
    /* background-image: url("{% static 'images-2019/bg-10.png' %}"); */
    /* background-color: #000; */
    background-image: url("{% static 'images-2019/bg-10.png' %}");
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
    font: 16px/1.6 Arial, sans-serif; 
    height: 100vh;
}


main{
    margin-top: 150px;
    display: flex;
    height: 65vh;
    
}

/*   ---------------------------    SIDE BAR   -------------------------------- */
.side-bar-wrapper {
    width: 20%;
    background: white;
    padding: 0 10px 0 35px;
}

/*   ------------------ team info  ------------------ */

.side-bar-wrapper .team-info{
    padding-left: 3vw;
}
.side-bar-wrapper .team-info .team-name h2{             /*  name size */
    font-size: 2.3rem;
    font-weight: bolder;
    margin-bottom: 25px;
}
.side-bar-wrapper .team-info .team-balance h5 {
    font-size: 1.6em;
    font-weight: 600;
    
}


/*   ------------------ Buttons  ------------------ */
.requestButtons{
    margin-top: 30px;
}
.requestButtons .req-btn{
    margin-bottom: 10px;
    /* width: 100%; */
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    text-align: center;
}
.requestButtons .req-btn:hover{
    cursor: pointer;
    text-align: center;
}
.requestButtons .req-btn a{
    width: 100%;
    padding: 15px 10px;
    background: tomato;
}


/*   ---------------------------    table   -------------------------------- */

/* overriding  */
table{
    background: transparent;
}
.stock-table{
    width: 50%;
    padding-left: 10vh;
    margin-left: 10%;
    padding: 10px;
    margin-top: -15px;
    
}

.stock-table .stockTableInsider table {
    background: transparent;
}
.stock-table .stockTableInsider .talberow{
    background: none;

}
.stockTableInsider thead{
    height: 70px;
    background: none;
    border: none;
    border-bottom: 2px solid #fff;
    background-image: linear-gradient(to right, #423366d0, #295763d0);
}

.stockTableInsider thead th{
    font-size: 2rem;
    text-align: center;
    height: 50px;
    color: white;
}

.stockTableInsider tbody{
    background: rgba(128, 128, 128, 0.308);
}

.stockTableInsider tbody tr{
    color: white;
}

.stockTableInsider tbody td{
    text-align: center;
    font-size: 1.3rem;
    margin-right: 1px;
    padding-right: 10px;
    color: white;
}

th, table tr:nth-of-type(2n){
    border: none;
    background: none;
}

th, table tr:nth-of-type(2n) td{
    border: none;
    background: none;
}

@media (max-width: 425px) {

    main{
        margin-top: 50px;
        /* display: flexbox; */
        /* flex-direction: column-reverse; */
        
    }
}

    </style>    
  </head>
  <body>
    {% include "navbar.html" %}
    
    <main class="mainpage">

      
      <div class="side-bar-wrapper">
          
            <div class="team-info">
              <div class="team-name"><h2>{{ user.username }}</h2></div>
              <div class="team-balance">    
                {% for dd in dashdata %}
                <h5>Team Balance {{ dd.userbalance }}</h5>
                {% endfor %}
              </div>
            </div>

            <div class="requestButtons">
              <div class="req-btn"><a class="btn-insider" href="{% url 'core:sentreq' %}">Requests Sent</a></div>
              <div class="req-btn"><a class="btn-insider" href="{% url 'core:receivedreq' %}">Received Requests</a></div>
              <div class="req-btn"><a class="btn-insider" href="{% url 'core:createrequest' %}">Create Trade Request</a></div>
              <div class="req-btn"><a class="btn-insider" href="{% url 'core:report' %}">Report(Insider Trading)</a></div>
              <div class="req-btn"><a class="btn-insider" href="{ url 'core:transaction-history' %}">transaction history</a></div>
          </div>
          
      </div>

      <!--    ----------------- STOCKS TABLE -------------------     -->
        <div class="stock-table">
            
              <table class="stockTableInsider">
                
                <thead >
                  <th>Stock Name</th>
                  <th>Number Of Stocks</th>
                  {% comment %}
                  <th>Current Price</th>
                  {% endcomment %}
                </thead>
                
                <tbody>

                  {% comment %} {% for dd in dashdata %}
                  <tr class="tablerow1">
                    <td>{{ dd.stock }}</td>
                    <td>{{ dd.numberofstocks }}</td>
                    <td>{{ dd.priceperstock }}</td>
                  </tr>
                  {% endfor %} {% endcomment %} {% for dd in dashdata %}
                  <tr class="tablerow">
                    <td>Stock1</td>
                    <td>{{dd.stock1}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock2</td>
                    <td>{{dd.stock2}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock3</td>
                    <td>{{dd.stock3}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock4</td>
                    <td>{{dd.stock4}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock5</td>
                    <td>{{dd.stock5}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock6</td>
                    <td>{{dd.stock6}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock7</td>
                    <td>{{dd.stock7}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock8</td>
                    <td>{{dd.stock8}}</td>
                  </tr>
                  <tr class="tablerow">
                    <td>Stock9</td>
                    <td>{{dd.stock9}}</td>
                  </tr>
                  <tr class="lastrow talberow">
                    <td>Stock10</td>
                    <td>{{dd.stock10}}</td>
                  </tr>
                  {% endfor %}

                  
                </tbody>
              </table>
            
            
      </div>
      
 </main>
    
    {% include "footer.html" %}
  </body>
</html>
{% endblock content %}

wds/templates/footer.html
{% load static %}
        <!-- ---------- FOOTER --------- -->
    
        <footer>
  <div class="container">
    <div class="row">
      
      <div class="col-lg-4 col-md-6">
        <h3>Site Map</h3>
        <ul class="list-unstyled three-column">
          <li>Home</li>
          <li>Services</li>
          <li>About</li>
          <li>Code</li>
          <li>Design</li>
          <li>Host</li>
          <li>Contact</li>
          <li>Company</li>
        </ul>
        <ul class="list-unstyled socila-list">
          <li><img src="http://placehold.it/48x48" alt="" /></li>
          <li><img src="http://placehold.it/48x48" alt="" /></li>
          <li><img src="http://placehold.it/48x48" alt="" /></li>
          <li><img src="http://placehold.it/48x48" alt="" /></li>
          <li><img src="http://placehold.it/48x48" alt="" /></li>
          <li><img src="http://placehold.it/48x48" alt="" /></li>
        </ul>
      </div>   
      
  </div>
</footer>

wds/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<body>
<header role="banner" class="position-absolute">
    <!-- Top Navigation -->
{% include "navbar.html" %}
</header>
{% include "nav-carousel.html" %}

<!-- Section 1 -->
<section class="portion section background-black text-center">
    <div class="line">
        <h1 class="head text text-size-50 text-m-size-40">
        Welcome to <b>WDS</b></h1>
        <p class="para text-size-20">Humans have come very far in their knowledge of money. From the barter system to the stock market, from copper tokens to printed notes, we have covered quite a journey. 
            For all the zealous participants out there, The Econ Club releases the teaser for their annual flagship event "Wolf of Dalal Street". Brush up your knowledge about domestic and international markets, and get ready to tackle the bull and the bear. Turn your losses into profits with your prudence and prove to the world that money indeed grows on trees!</p>
        
        {% if user.is_authenticated %}
        <a href="{% url 'core:dashboard' %}" class="s-12 m-6 l-3 center button border-radius background-purple text-size-20 margin-top-60 text-white">Enter WDS</a>
        {% else %}
        <a href="{% url 'core:userlogin' %}" class="s-12 m-6 l-3 center button border-radius background-purple text-size-20 margin-top-60 text-white">Enter WDS</a>
        {% endif %}
        
    </div>
</section>

<!-- Section 2 -->
<section class="section" data-image-src="{% static 'images-2019/bg-5.jpg'%}">
    <div class="line">
        <div class="s-12 m-12 l-6">
            <h2 class="text-size-50 text-white">
            Stock Market</h2>
            <h2 class="text-size-30 text-white">
                What you will Gain from this event??</h2>
            <p class="margin-bottom">Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis
                nisl ut aliquip ex ea commodo consequat.</p>
            
            <!-- white Start your Business object -->
            <!--<img class="margin-left-20 margin-top-30 margin-bottom-60" src="img/start-your-business.svg" alt="">-->
        </div>
    </div>
    <!-- white full width arrow object -->
    <img class="arrow-object" src="img/arrow-object-white.svg" alt="">
</section>


<section class="portion section-top-padding background-dark-hightlight">
    <div class="line text-center">
        <i class="icon-sli-people text-white text-size-40"></i>
        <h2 class="text-white text-size-50 text-m-size-40">Our <b>Sponsors</b></h2>
        </br>       
    </div>
    <div class="line">
        <div class="carousel-blocks owl-carousel">
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/index.png'%}" />
                </div>
                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Frank Star</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Web Designer</p>
                    <div class="line">
                        <a href="/"><i class="icon-linked_in_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-google_plus_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-twitter_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/sp2.jpg'%}" />
                </div>
                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Jane Naismith</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Graphic Designer</p>
                    <div class="line">
                        <a href="/"><i class="icon-facebook_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-instagram_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/sp2.jpg'%}" />
                </div>
                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Mark Stoner</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Boss</p>
                    <div class="line">
                        <a href="/"><i class="icon-linked_in_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-instagram_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/index.png'%}" />
                </div>
                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Steve Carpenter</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Web Developer</p>
                    <div class="line">
                        <a href="/"><a href="/"><i class="icon-google_plus_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-instagram_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-twitter_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/sp2.jpg'%}" />
                </div>
                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Steff Kingston</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Account Manager</p>
                    <div class="line">
                        <a href="/"><i class="icon-linked_in_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-google_plus_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-instagram_circle text-primary-hover text-size-25"></i></a>                                <a href="/"><i class="icon-twitter_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="image-border-radius image-with-hover-overlay">
                    <div class="image-hover-overlay background-purple">
                        <div class="image-hover-overlay-content padding">
                            <p>Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat.</p>
                        </div>
                    </div>
                    <img src="{% static 'images-2019/sp2.jpg'%}" />
                </div>

                <div class="margin-top">
                    <h4 class="text-strong margin-bottom-10">Melissa Style</h4>
                    <p class="margin-bottom-10 text-purple text-uppercase">Programmer</p>
                    <div class="line">
                        <a href="/"><i class="icon-linked_in_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-google_plus_circle text-primary-hover text-size-25"></i></a> <a href="/"><i class="icon-instagram_circle text-primary-hover text-size-25"></i></a>                                <a href="/"><i class="icon-twitter_circle text-primary-hover text-size-25"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <a href="https://sites.google.com/view/econclub/about?authuser=0" class="s-12 m-6 l-3 center button border-radius background-purple text-size-20 margin-top-60 text-white">About Us</a>
        </br>
    </div>
</section>
</body>

{% include "footer.html" %}
{% endblock content %}

wds/templates/navbar.html
{% load static %}
        <nav class="background-transparent background-dark-dott full-width sticky">
            <!-- mobile version logo -->
            <div class="logo hide-l hide-xl hide-xxl">
                <a href="index.html" class="logo">
                    <!-- Logo Dark Version -->
                    <img class="logo-dark" src="{% static 'img/logo-dark.svg'%}" alt="">
                </a>
            </div>
            <div class="top-nav">

                <!-- left menu items -->
                <div class="top-nav left-menu">
                    <ul class="right top-ul chevron">
                        <li class="active-item">
                            <a href="{% url 'core:home' %}">Home</a>
                            
                        </li>
                        <li>
                            <a href="{% url 'core:stocks' %}">&nbsp Stocks</a>
                            
                        </li>
                       
                    </ul>
                </div>

                <!-- logo -->
                <ul class="logo-menu">
                    <a href="{% url 'core:home' %}" class="logo">
                        <!-- Logo White Version -->
                        <img class="logo-white" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                        <!-- Logo Dark Version -->
                        <img class="logo-dark" src="{% static 'images-2019/WDS_Logo_Black.png'%}" alt="">
                        
                    </a>
                </ul>
                
                <!-- right menu items -->
                <div class="top-nav right-menu">
                    <ul class="top-ul chevron">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'core:news' %}">&nbsp News</a></li>
                        <li><a href="{% url 'core:dashboard' %}">&nbsp Dashboard</a></li>
                        <li><a href="{% url 'core:userlogout' %}">&nbsp Logout</a></li>
                        {% else %}
                        <li><a href="{% url 'core:news' %}">&nbsp News</a></li>
                        <li><a href="{% url 'core:userlogin' %}">&nbsp Login</a></li>
                        {% endif %}
                        
                                        
                    </ul>
                </div>
            </div>
        </nav>
        

wds/templates/news.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<style>
  body {
        background-image: url("{% static 'images-2019/2.jpg' %}");
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        font: 16px/1.6 Arial, sans-serif;
      }
  .iframe-container{
  position: relative;
  width: 100%;
  padding-bottom: 56.25%; 
  height: 0;
}
.iframe-container iframe{
  position: absolute;
  top:0;
  left: 0;
  width: 100%;
  height: 100%;
}
.cont{
    width: 70%;
    height: 60%;
    
    margin: auto;
    background-color: azure;
}
h1 {
    font-size:4rem;
    color: white;
    font-weight: bold;
    margin-top: 15vh;
    margin-bottom: 0;
    z-index: 1 !important;
}
p{
    font-size:2.5rem;
    color: black;
    font-weight: bold;
    line-height: 1;
}
.container{
    text-align: center;
}
</style>



<body>

        <!-- Top Navigation -->
    {% include "navbar.html" %}
    </header>
    <div class="container">
    <h1>NEWS</h1>
    <div class="card">  
        <div class="card-body">
            <h4 class="card-text">Stock Market is not all about trading.How well you understand your surroundings will decide whether you gain or lose.So watch the NEWS carefully!</h4>
        </div>
    </div>
 
    <div class="cont">
        
        <div class="iframe-container">
            <iframe width="1000" height="500" src="https://www.youtube-nocookie.com/embed/57MhCvW9caw" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>



{%endblock%}

wds/templates/received_request.html
<html>

<body><h1>recieved requests</h1>
<table border="1">
if action=sell that means you are the buyer and if action = buy then you are the seller 
<tr><th>sender</th><th>type</th><th>stock</th><th>number of stocks</th><th>priceperstock</th><th>accept</th><th>delete</th></tr>
{% for req in requests %}
<tr><td>{{ req.sender }}</td>
<td>{{ req.action }} </td>
<td>{{ req.stock }} </td>
<td>{{ req.numberofstocks }}</td>
<td>{{ req.priceperstock }}</td>
<td><a href="{% url 'core:accept-request' req.id %}">accept</a></td>
<td><a href="{% url 'core:decline-request' req.id %}">decline</a></td>
{% comment  %}
<td> <button id="accept" onclick='triggerAcceptFriendRequest("{{ req.id }}")'>accept</button></td>   
<td> <button id="decline">decline</button></td>
{% endcomment %}

</tr>
{% endfor %}

</table>
<script type="text/javascript">
    function onFriendRequestAccepted(){
		location.reload();
	}

	function onFriendRequestDeclined(){
		location.reload();
	}

	function triggerAcceptFriendRequest(friend_request_id){
		acceptFriendRequest(friend_request_id, onFriendRequestAccepted)
	}

	function triggerDeclineFriendRequest(friend_request_id){
		declineFriendRequest(friend_request_id, onFriendRequestDeclined)
	}
    function acceptFriendRequest(friend_request_id, uiUpdateFunction){
		var url = "{% url 'core:accept-request' friend_request_id=53252623623632623 %}".replace("53252623623632623", friend_request_id)
		$.ajax({
			type: 'GET',
			dataType: "json",
			url: url,
			timeout: 5000,
			success: function(data) {
				console.log("SUCCESS", data)
				if(data['response'] == "request accepted"){
					// ui is updated
				}
				else if(data['response'] != null){
					alert(data['response'])
				}
			},
			error: function(data) {
				console.error("ERROR...", data)
				alert("Something went wrong.")
			},
			complete: function(data){
				uiUpdateFunction()
			}
		});
	}
</script>
</body></html>

wds/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div>
    <h1>Register here</h1>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>
</div>
{% endblock content %}

wds/templates/report.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div>
    <h1>Report</h1>
    <h2>If you reported correctly you will be rewarded Rs.5000</h2><br>
    <h2>But if you reported wrong the same amount will be deducted from you!!</h2>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info">Submit</button>
    </form>
</div>
{% endblock content %}

wds/templates/sell-form.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}


<div>
    <h1>Fill the form to buy/sell stocks!</h1>
    <form method='POST' enctype="\application/x-www-form-urlencoded">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-outline-info" id="id_send_sell_request_btn">Send Request</button>
    </form>
</div>



{% endblock %}

wds/templates/sent_requests.html
<html>

<body><h1>waiting for confirmation from another user</h1>
<table border="1">
<tr><th>receiver</th><th>type</th><th>stock</th><th>number of stocks</th><th>priceperstock</th><th>Cancel</th></tr>
{% for req in requests %}
<tr><td>{{ req.receiver }}</td>
<td>{{ req.action }} </td>
<td>{{ req.stock }} </td>
<td>{{ req.numberofstocks }}</td>
<td>{{ req.priceperstock }}</td>   
<td> <a href="{% url 'core:cancel-request' req.id %}">Cancel</a></td>
</tr>
{% endfor %}
</table>
</body></html>

wds/templates/stocks.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<head>
<style>
  body{
background-image: url("{% static 'images-2019/bg-9.jpg' %}");
background-attachment: fixed;
background-position: center;
background-repeat: no-repeat;
background-size: cover;
font:16px/1.6 Arial,  sans-serif;
}
.cs{
  color: white;
  font-size: 40px;
}
</style>
</head>
<body>
    <header role="banner" class="position-absolute">
      <!-- Top Navigation -->
    {% include "navbar.html" %}
  </header>

    <div class="form-group">
        
        <a class="btn btn-outline-secondary" href="{% url 'core:createrequest' %}">Create Trade Request</a>
      </div>
      &nbsp;
      <h1 class="cs"><b>All Available Stocks</b></h1>
      <div class="container">
        
      <table class="table table-primary table-bordered table-hover">
        <thead>
          <th>Stock Name</th>
          <th>Current Price</th>
        </thead>

              {% for post in posts %}
              <tr>
                <td>{{ post.stockname }}</td>
                <td>{{ post.price }}</td>
              </tr>
              {% endfor %}

      </table>

    </div>
  
{% include "footer.html" %}
</body>

{% endblock %}

wds/templates/transaction-history.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<html>

<body><h1>Transaction Log</h1>
<table border="1">
<tr><th>receiver</th><th>type</th><th>stock</th><th>number of stocks</th><th>priceperstock</th><th>Status</th></tr>
{% for req in requests %}

<tr><td>{{ req.receiver }}</td>
<td>{{ req.action }} </td>
<td>{{ req.stock }} </td>
<td>{{ req.numberofstocks }}</td>
<td>{{ req.priceperstock }}</td> 
<td>{{ req.status }}</td>
</tr>
{% endfor %}
</table>
</body></html>



{% endblock %}